#!/bin/sh
#
# Description:	Manages an NGINX instance as an OCF High-Availability resource
#								under Heartbeat/LinuxHA control
#
# Author:	Joe Khoobyar
#
# License:	GNU General Public License (GPL)
#
# Copyright (c) 2009 All Rights Reserved
#
# See usage() function below for more details...
#
# OCF instance parameters:
#   OCF_RESKEY_nginx
#   OCF_RESKEY_config
#		OCF_RESKEY_pid
#   OCF_RESKEY_pid_owner
#   OCF_RESKEY_pid_group
#		OCF_RESKEY_options
#   OCF_RESKEY_renice
#		OCF_RESKEY_monitor_url

#######################################################################
# Initialization:

. ${OCF_ROOT:-/usr/lib/ocf}/resource.d/heartbeat/.ocf-shellfuncs
. $(dirname $0)/.jk-shellfuncs

#######################################################################

: ${OCF_RESKEY_nginx="/usr/sbin/nginx"}
: ${OCF_RESKEY_config="/etc/nginx/nginx.conf"}
: ${OCF_RESKEY_pid="/var/run/nginx.pid"}
: ${OCF_RESKEY_pid_owner="nobody"}
: ${OCF_RESKEY_pid_group="nobody"}

usage() {
cat <<END

usage: $0 (start|stop|status|reload|monitor|meta-data|validate-all)

$0 manages NGINX as an OCF resource.

The 'start' operation starts NGINX.
The 'stop' operation stops NGINX.
The 'status' operation reports whether NGINX is running.
The 'reload' operation gracefully reloads NGINX.
The 'monitor' operation reports whether NGINX seems to be working.
The 'meta-data' operation reports the configuration options.
The 'validate-all' operation reports whether the parameters are valid.

END
}

meta_data() {
cat <<END

<?xml version="1.0" ?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="NGINX">
    <version>1.0</version>
      <longdesc lang="en">This is an OCF resource agent for the NGINX web server</longdesc>
      <shortdesc lang="en">OCF resource agent for NGINX</shortdesc>
      <parameters>
				<parameter name="nginx" required="1" unique="0">
					<longdesc lang="en">
						Full path to the NGINX executable.
					</longdesc>
					<shortdesc>NGINX executable</shortdesc>
					<content type="string" default="/usr/sbin/nginx"/>
				</parameter>
				<parameter name="config" required="1" unique="1">
					<longdesc lang="en">
						Full path to the NGINX configuration file for this instance.
					</longdesc>
					<shortdesc>Config file</shortdesc>
					<content type="string" default="/etc/nginx/nginx.conf"/>
				</parameter>
				<parameter name="pid" required="1" unique="1">
					<longdesc lang="en">
						Full path to the PID file that this instance should use.
					</longdesc>
					<shortdesc>PID file</shortdesc>
					<content type="string" default="/var/run/nginx.pid"/>
				</parameter>
				<parameter name="pid_owner" required="0">
					<longdesc lang="en">
						User who should own the PID file.
					</longdesc>
					<shortdesc>PID file owner</shortdesc>
					<content type="string" default="nobody"/>
				</parameter>
				<parameter name="pid_group" required="0">
					<longdesc lang="en">
						Group which should own the PID file.
					</longdesc>
					<shortdesc>PID file group</shortdesc>
					<content type="string" default="nobody"/>
				</parameter>
				<parameter name="options" required="0">
					<longdesc lang="en">
						Any additional options to pass to the NGINX command.
					</longdesc>
					<shortdesc>Extra options</shortdesc>
					<content type="string" default=""/>
				</parameter>
				<parameter name="renice" required="0">
					<longdesc lang="en">
						Optional value to pass to renice NGINX with after starting it.
					</longdesc>
					<shortdesc>renice value</shortdesc>
					<content type="string" default=""/>
				</parameter>
				<parameter name="monitor_url" required="0">
					<longdesc lang="en">
						Optional URL to use for monitoring NGINX with wget when the
						OCF_CHECK_LEVEL is 10 or above.
					</longdesc>
					<shortdesc>URL to monitor</shortdesc>
					<content type="string" default=""/>
				</parameter>
		</parameters>
    <actions>
      <action name="start" timeout="30" />
      <action name="stop" timeout="30" />
      <action name="status" timeout="20" />
      <action name="monitor" depth="0" start-delay="10" interval="10" timeout="30" />
      <action name="meta-data" timeout="5" />
      <action name="validate-all" timeout="5" />
   </actions>
</resource-agent>

END
}

NGINX="$OCF_RESKEY_nginx -c $OCF_RESKEY_config $OCF_RESKEY_options"

nginx_validate() {
	jk_validate_executable "$OCF_RESKEY_nginx"
	jk_validate_config "$NGINX -t" "$OCF_RESKEY_config"
}

nginx_status() {
	jk_resource_status_by_pid 'NGINX'
}

nginx_monitor() {
	local retval
	nginx_status; retval=$?
	if [ $OCF_CHECK_LEVEL -lt 10 -o $retval -ne 0 ]; then
		jk_monitor_url
	else
		return $retval
	fi
}

nginx_start() {
	local retval

	if nginx_status; then
		ocf_log debug "NGINX is already running"
		return $OCF_SUCCESS
	fi

	jk_pidfile_prepare && ERRORS=`$NGINX 2>&1`
	retval=$?
	[ -z "$ERRORS" -a "$retval" -ne 0 ] && ERRORS="error code $retval"

	if [ $retval -ne $OCF_SUCCESS ]; then
		ocf_log err "NGINX failed to start: $ERRORS"
		return $OCF_ERR_GENERIC
	else
		[ -z $OCF_RESKEY_renice ] || renice $OCF_RESKEY_renice $OCF_RESKEY_pid || true
	fi

	return $OCF_SUCCESS
}

nginx_reload() {
	jk_resource_signal_by_pid 'NGINX', 'HUP'
}

nginx_stop() {
	jk_resource_stop_by_pid 'NGINX'
}

# What kind of method was invoked?
case "$1" in
  start)	nginx_validate; nginx_start;;
  stop)		nginx_stop;;
  status)	nginx_status;;
  reload)	nginx_reload;;
  monitor)	nginx_monitor;;
  meta-data)	meta_data; exit $OCF_SUCCESS;;
  validate-all)	nginx_validate; exit $OCF_SUCCESS;;
  *)		usage; exit $OCF_ERR_UNIMPLEMENTED;;
esac
exit $?
